# Generated by Django 5.0 on 2023-12-30 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twat", "0004_profile_profile_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/images/profile-image/"
            ),
        ),
        migrations.AlterField(
            model_name="twat",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="twat_like", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
