# Generated by Django 4.2.6 on 2023-10-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Введите название поста", max_length=70),
                ),
                ("text", models.TextField(help_text="Содержание Статьи")),
                (
                    "time_created",
                    models.DateTimeField(
                        db_comment="Date and time when the article was published"
                    ),
                ),
            ],
        ),
    ]
