# Generated by Django 4.2.6 on 2023-10-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="PostNews",
        ),
    ]
