# Generated by Django 4.2.6 on 2023-10-29 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_rename_post_postnews"),
    ]

    operations = [
        migrations.AddField(
            model_name="postnews",
            name="time_modified",
            field=models.DateTimeField(
                auto_now_add=True,
                db_comment="Date and time when the article was modified",
                default=django.utils.timezone.now,
                null=None,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="postnews",
            name="time_created",
            field=models.DateTimeField(
                auto_now_add=True,
                db_comment="Date and time when the article was published",
            ),
        ),
    ]
