# Generated by Django 4.2.6 on 2023-10-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_postnews_time_modified_alter_postnews_time_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postnews",
            name="time_modified",
            field=models.DateTimeField(
                auto_now=True,
                db_comment="Date and time when the article was modified",
                null=None,
            ),
        ),
    ]
