# Generated by Django 4.2.6 on 2023-10-29 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0004_alter_postnews_time_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="postnews",
            name="author",
            field=models.ForeignKey(
                blank=None,
                default=1,
                null=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
