# Generated by Django 4.2.6 on 2023-11-07 13:27

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_postnews_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postnews",
            name="author",
            field=models.CharField(default=registration.models.User),
        ),
    ]
