# Generated by Django 4.2.6 on 2023-10-31 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_postnews_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postnews",
            name="author",
        ),
    ]
