# Generated by Django 4.2.6 on 2023-10-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_remove_postnews_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postnews",
            name="time_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="postnews",
            name="time_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
