# Generated by Django 4.2 on 2023-11-14 13:43

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                keep_meta=True,
                null=True,
                quality=75,
                scale=0.5,
                size=[300, 200],
                upload_to="static/images",
            ),
        ),
    ]
